/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as VendorLoginRouteImport } from './routes/vendor-login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ControlRouteImport } from './routes/control'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppSuperAdminRouteImport } from './routes/_app/super-admin'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppClientRouteImport } from './routes/_app/client'
import { Route as AppCheckoutRouteImport } from './routes/_app/checkout'
import { Route as AppVendorRouteImport } from './routes/_app/_vendor'
import { Route as AppAdminRouteImport } from './routes/_app/_admin'
import { Route as AppSuperAdminIndexRouteImport } from './routes/_app/super-admin/index'
import { Route as ApiPublicWooWebhookRouteImport } from './routes/api/public/woo-webhook'
import { Route as AppSuperAdminUsersRouteImport } from './routes/_app/super-admin/users'
import { Route as AppSuperAdminCompaniesRouteImport } from './routes/_app/super-admin/companies'
import { Route as AppVendorVendorIndexRouteImport } from './routes/_app/_vendor/vendor.index'
import { Route as AppAdminAdminIndexRouteImport } from './routes/_app/_admin/admin.index'
import { Route as AppVendorVendorTeamRouteImport } from './routes/_app/_vendor/vendor.team'
import { Route as AppVendorVendorStorageHealthRouteImport } from './routes/_app/_vendor/vendor.storage-health'
import { Route as AppVendorVendorProductsRouteImport } from './routes/_app/_vendor/vendor.products'
import { Route as AppVendorVendorOrdersRouteImport } from './routes/_app/_vendor/vendor.orders'
import { Route as AppVendorVendorInvoicesRouteImport } from './routes/_app/_vendor/vendor.invoices'
import { Route as AppVendorVendorBrandingRouteImport } from './routes/_app/_vendor/vendor.branding'
import { Route as AppVendorVendorAnalyticsRouteImport } from './routes/_app/_vendor/vendor.analytics'
import { Route as AppVendorVendorActivityRouteImport } from './routes/_app/_vendor/vendor.activity'
import { Route as AppAdminAdminCompaniesRouteImport } from './routes/_app/_admin/admin.companies'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLoginRoute = VendorLoginRouteImport.update({
  id: '/vendor-login',
  path: '/vendor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuperAdminRoute = AppSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppClientRoute = AppClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorRoute = AppVendorRouteImport.update({
  id: '/_vendor',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminIndexRoute = AppSuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSuperAdminRoute,
} as any)
const ApiPublicWooWebhookRoute = ApiPublicWooWebhookRouteImport.update({
  id: '/api/public/woo-webhook',
  path: '/api/public/woo-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuperAdminUsersRoute = AppSuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSuperAdminRoute,
} as any)
const AppSuperAdminCompaniesRoute = AppSuperAdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppSuperAdminRoute,
} as any)
const AppVendorVendorIndexRoute = AppVendorVendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppAdminAdminIndexRoute = AppAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVendorVendorTeamRoute = AppVendorVendorTeamRouteImport.update({
  id: '/vendor/team',
  path: '/vendor/team',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppVendorVendorStorageHealthRoute =
  AppVendorVendorStorageHealthRouteImport.update({
    id: '/vendor/storage-health',
    path: '/vendor/storage-health',
    getParentRoute: () => AppVendorRoute,
  } as any)
const AppVendorVendorProductsRoute = AppVendorVendorProductsRouteImport.update({
  id: '/vendor/products',
  path: '/vendor/products',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppVendorVendorOrdersRoute = AppVendorVendorOrdersRouteImport.update({
  id: '/vendor/orders',
  path: '/vendor/orders',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppVendorVendorInvoicesRoute = AppVendorVendorInvoicesRouteImport.update({
  id: '/vendor/invoices',
  path: '/vendor/invoices',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppVendorVendorBrandingRoute = AppVendorVendorBrandingRouteImport.update({
  id: '/vendor/branding',
  path: '/vendor/branding',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppVendorVendorAnalyticsRoute =
  AppVendorVendorAnalyticsRouteImport.update({
    id: '/vendor/analytics',
    path: '/vendor/analytics',
    getParentRoute: () => AppVendorRoute,
  } as any)
const AppVendorVendorActivityRoute = AppVendorVendorActivityRouteImport.update({
  id: '/vendor/activity',
  path: '/vendor/activity',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppAdminAdminCompaniesRoute = AppAdminAdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/vendor-login': typeof VendorLoginRoute
  '/vendors': typeof VendorsRoute
  '/checkout': typeof AppCheckoutRoute
  '/client': typeof AppClientRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/settings': typeof AppSettingsRoute
  '/super-admin': typeof AppSuperAdminRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/store/$slug': typeof StoreSlugRoute
  '/super-admin/companies': typeof AppSuperAdminCompaniesRoute
  '/super-admin/users': typeof AppSuperAdminUsersRoute
  '/api/public/woo-webhook': typeof ApiPublicWooWebhookRoute
  '/super-admin/': typeof AppSuperAdminIndexRoute
  '/admin/companies': typeof AppAdminAdminCompaniesRoute
  '/vendor/activity': typeof AppVendorVendorActivityRoute
  '/vendor/analytics': typeof AppVendorVendorAnalyticsRoute
  '/vendor/branding': typeof AppVendorVendorBrandingRoute
  '/vendor/invoices': typeof AppVendorVendorInvoicesRoute
  '/vendor/orders': typeof AppVendorVendorOrdersRoute
  '/vendor/products': typeof AppVendorVendorProductsRoute
  '/vendor/storage-health': typeof AppVendorVendorStorageHealthRoute
  '/vendor/team': typeof AppVendorVendorTeamRoute
  '/admin/': typeof AppAdminAdminIndexRoute
  '/vendor/': typeof AppVendorVendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/vendor-login': typeof VendorLoginRoute
  '/vendors': typeof VendorsRoute
  '/checkout': typeof AppCheckoutRoute
  '/client': typeof AppClientRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/store/$slug': typeof StoreSlugRoute
  '/super-admin/companies': typeof AppSuperAdminCompaniesRoute
  '/super-admin/users': typeof AppSuperAdminUsersRoute
  '/api/public/woo-webhook': typeof ApiPublicWooWebhookRoute
  '/super-admin': typeof AppSuperAdminIndexRoute
  '/admin/companies': typeof AppAdminAdminCompaniesRoute
  '/vendor/activity': typeof AppVendorVendorActivityRoute
  '/vendor/analytics': typeof AppVendorVendorAnalyticsRoute
  '/vendor/branding': typeof AppVendorVendorBrandingRoute
  '/vendor/invoices': typeof AppVendorVendorInvoicesRoute
  '/vendor/orders': typeof AppVendorVendorOrdersRoute
  '/vendor/products': typeof AppVendorVendorProductsRoute
  '/vendor/storage-health': typeof AppVendorVendorStorageHealthRoute
  '/vendor/team': typeof AppVendorVendorTeamRoute
  '/admin': typeof AppAdminAdminIndexRoute
  '/vendor': typeof AppVendorVendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/vendor-login': typeof VendorLoginRoute
  '/vendors': typeof VendorsRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/_vendor': typeof AppVendorRouteWithChildren
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/client': typeof AppClientRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/super-admin': typeof AppSuperAdminRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/store/$slug': typeof StoreSlugRoute
  '/_app/super-admin/companies': typeof AppSuperAdminCompaniesRoute
  '/_app/super-admin/users': typeof AppSuperAdminUsersRoute
  '/api/public/woo-webhook': typeof ApiPublicWooWebhookRoute
  '/_app/super-admin/': typeof AppSuperAdminIndexRoute
  '/_app/_admin/admin/companies': typeof AppAdminAdminCompaniesRoute
  '/_app/_vendor/vendor/activity': typeof AppVendorVendorActivityRoute
  '/_app/_vendor/vendor/analytics': typeof AppVendorVendorAnalyticsRoute
  '/_app/_vendor/vendor/branding': typeof AppVendorVendorBrandingRoute
  '/_app/_vendor/vendor/invoices': typeof AppVendorVendorInvoicesRoute
  '/_app/_vendor/vendor/orders': typeof AppVendorVendorOrdersRoute
  '/_app/_vendor/vendor/products': typeof AppVendorVendorProductsRoute
  '/_app/_vendor/vendor/storage-health': typeof AppVendorVendorStorageHealthRoute
  '/_app/_vendor/vendor/team': typeof AppVendorVendorTeamRoute
  '/_app/_admin/admin/': typeof AppAdminAdminIndexRoute
  '/_app/_vendor/vendor/': typeof AppVendorVendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/control'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/vendor-login'
    | '/vendors'
    | '/checkout'
    | '/client'
    | '/notifications'
    | '/orders'
    | '/settings'
    | '/super-admin'
    | '/auth/callback'
    | '/store/$slug'
    | '/super-admin/companies'
    | '/super-admin/users'
    | '/api/public/woo-webhook'
    | '/super-admin/'
    | '/admin/companies'
    | '/vendor/activity'
    | '/vendor/analytics'
    | '/vendor/branding'
    | '/vendor/invoices'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/storage-health'
    | '/vendor/team'
    | '/admin/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/control'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/vendor-login'
    | '/vendors'
    | '/checkout'
    | '/client'
    | '/notifications'
    | '/orders'
    | '/settings'
    | '/auth/callback'
    | '/store/$slug'
    | '/super-admin/companies'
    | '/super-admin/users'
    | '/api/public/woo-webhook'
    | '/super-admin'
    | '/admin/companies'
    | '/vendor/activity'
    | '/vendor/analytics'
    | '/vendor/branding'
    | '/vendor/invoices'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/storage-health'
    | '/vendor/team'
    | '/admin'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/control'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/vendor-login'
    | '/vendors'
    | '/_app/_admin'
    | '/_app/_vendor'
    | '/_app/checkout'
    | '/_app/client'
    | '/_app/notifications'
    | '/_app/orders'
    | '/_app/settings'
    | '/_app/super-admin'
    | '/auth/callback'
    | '/store/$slug'
    | '/_app/super-admin/companies'
    | '/_app/super-admin/users'
    | '/api/public/woo-webhook'
    | '/_app/super-admin/'
    | '/_app/_admin/admin/companies'
    | '/_app/_vendor/vendor/activity'
    | '/_app/_vendor/vendor/analytics'
    | '/_app/_vendor/vendor/branding'
    | '/_app/_vendor/vendor/invoices'
    | '/_app/_vendor/vendor/orders'
    | '/_app/_vendor/vendor/products'
    | '/_app/_vendor/vendor/storage-health'
    | '/_app/_vendor/vendor/team'
    | '/_app/_admin/admin/'
    | '/_app/_vendor/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ControlRoute: typeof ControlRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VendorLoginRoute: typeof VendorLoginRoute
  VendorsRoute: typeof VendorsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  StoreSlugRoute: typeof StoreSlugRoute
  ApiPublicWooWebhookRoute: typeof ApiPublicWooWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-login': {
      id: '/vendor-login'
      path: '/vendor-login'
      fullPath: '/vendor-login'
      preLoaderRoute: typeof VendorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/super-admin': {
      id: '/_app/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AppSuperAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client': {
      id: '/_app/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AppClientRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_vendor': {
      id: '/_app/_vendor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppVendorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/': {
      id: '/_app/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AppSuperAdminIndexRouteImport
      parentRoute: typeof AppSuperAdminRoute
    }
    '/api/public/woo-webhook': {
      id: '/api/public/woo-webhook'
      path: '/api/public/woo-webhook'
      fullPath: '/api/public/woo-webhook'
      preLoaderRoute: typeof ApiPublicWooWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/super-admin/users': {
      id: '/_app/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AppSuperAdminUsersRouteImport
      parentRoute: typeof AppSuperAdminRoute
    }
    '/_app/super-admin/companies': {
      id: '/_app/super-admin/companies'
      path: '/companies'
      fullPath: '/super-admin/companies'
      preLoaderRoute: typeof AppSuperAdminCompaniesRouteImport
      parentRoute: typeof AppSuperAdminRoute
    }
    '/_app/_vendor/vendor/': {
      id: '/_app/_vendor/vendor/'
      path: '/vendor'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AppVendorVendorIndexRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/_admin/admin/': {
      id: '/_app/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_vendor/vendor/team': {
      id: '/_app/_vendor/vendor/team'
      path: '/vendor/team'
      fullPath: '/vendor/team'
      preLoaderRoute: typeof AppVendorVendorTeamRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/_vendor/vendor/storage-health': {
      id: '/_app/_vendor/vendor/storage-health'
      path: '/vendor/storage-health'
      fullPath: '/vendor/storage-health'
      preLoaderRoute: typeof AppVendorVendorStorageHealthRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/_vendor/vendor/products': {
      id: '/_app/_vendor/vendor/products'
      path: '/vendor/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof AppVendorVendorProductsRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/_vendor/vendor/orders': {
      id: '/_app/_vendor/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof AppVendorVendorOrdersRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/_vendor/vendor/invoices': {
      id: '/_app/_vendor/vendor/invoices'
      path: '/vendor/invoices'
      fullPath: '/vendor/invoices'
      preLoaderRoute: typeof AppVendorVendorInvoicesRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/_vendor/vendor/branding': {
      id: '/_app/_vendor/vendor/branding'
      path: '/vendor/branding'
      fullPath: '/vendor/branding'
      preLoaderRoute: typeof AppVendorVendorBrandingRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/_vendor/vendor/analytics': {
      id: '/_app/_vendor/vendor/analytics'
      path: '/vendor/analytics'
      fullPath: '/vendor/analytics'
      preLoaderRoute: typeof AppVendorVendorAnalyticsRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/_vendor/vendor/activity': {
      id: '/_app/_vendor/vendor/activity'
      path: '/vendor/activity'
      fullPath: '/vendor/activity'
      preLoaderRoute: typeof AppVendorVendorActivityRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/_admin/admin/companies': {
      id: '/_app/_admin/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AppAdminAdminCompaniesRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAdminCompaniesRoute: typeof AppAdminAdminCompaniesRoute
  AppAdminAdminIndexRoute: typeof AppAdminAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAdminCompaniesRoute: AppAdminAdminCompaniesRoute,
  AppAdminAdminIndexRoute: AppAdminAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppVendorRouteChildren {
  AppVendorVendorActivityRoute: typeof AppVendorVendorActivityRoute
  AppVendorVendorAnalyticsRoute: typeof AppVendorVendorAnalyticsRoute
  AppVendorVendorBrandingRoute: typeof AppVendorVendorBrandingRoute
  AppVendorVendorInvoicesRoute: typeof AppVendorVendorInvoicesRoute
  AppVendorVendorOrdersRoute: typeof AppVendorVendorOrdersRoute
  AppVendorVendorProductsRoute: typeof AppVendorVendorProductsRoute
  AppVendorVendorStorageHealthRoute: typeof AppVendorVendorStorageHealthRoute
  AppVendorVendorTeamRoute: typeof AppVendorVendorTeamRoute
  AppVendorVendorIndexRoute: typeof AppVendorVendorIndexRoute
}

const AppVendorRouteChildren: AppVendorRouteChildren = {
  AppVendorVendorActivityRoute: AppVendorVendorActivityRoute,
  AppVendorVendorAnalyticsRoute: AppVendorVendorAnalyticsRoute,
  AppVendorVendorBrandingRoute: AppVendorVendorBrandingRoute,
  AppVendorVendorInvoicesRoute: AppVendorVendorInvoicesRoute,
  AppVendorVendorOrdersRoute: AppVendorVendorOrdersRoute,
  AppVendorVendorProductsRoute: AppVendorVendorProductsRoute,
  AppVendorVendorStorageHealthRoute: AppVendorVendorStorageHealthRoute,
  AppVendorVendorTeamRoute: AppVendorVendorTeamRoute,
  AppVendorVendorIndexRoute: AppVendorVendorIndexRoute,
}

const AppVendorRouteWithChildren = AppVendorRoute._addFileChildren(
  AppVendorRouteChildren,
)

interface AppSuperAdminRouteChildren {
  AppSuperAdminCompaniesRoute: typeof AppSuperAdminCompaniesRoute
  AppSuperAdminUsersRoute: typeof AppSuperAdminUsersRoute
  AppSuperAdminIndexRoute: typeof AppSuperAdminIndexRoute
}

const AppSuperAdminRouteChildren: AppSuperAdminRouteChildren = {
  AppSuperAdminCompaniesRoute: AppSuperAdminCompaniesRoute,
  AppSuperAdminUsersRoute: AppSuperAdminUsersRoute,
  AppSuperAdminIndexRoute: AppSuperAdminIndexRoute,
}

const AppSuperAdminRouteWithChildren = AppSuperAdminRoute._addFileChildren(
  AppSuperAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppVendorRoute: typeof AppVendorRouteWithChildren
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppClientRoute: typeof AppClientRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuperAdminRoute: typeof AppSuperAdminRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppVendorRoute: AppVendorRouteWithChildren,
  AppCheckoutRoute: AppCheckoutRoute,
  AppClientRoute: AppClientRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuperAdminRoute: AppSuperAdminRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ControlRoute: ControlRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VendorLoginRoute: VendorLoginRoute,
  VendorsRoute: VendorsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  StoreSlugRoute: StoreSlugRoute,
  ApiPublicWooWebhookRoute: ApiPublicWooWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
