/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppQuickOrderRouteImport } from './routes/_app/quick-order'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppLoyaltyRouteImport } from './routes/_app/loyalty'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/_admin'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products.$productId'
import { Route as AppAdminAdminIndexRouteImport } from './routes/_app/_admin/admin.index'
import { Route as AppAdminAdminTerritoriesRouteImport } from './routes/_app/_admin/admin.territories'
import { Route as AppAdminAdminProductsRouteImport } from './routes/_app/_admin/admin.products'
import { Route as AppAdminAdminOrdersRouteImport } from './routes/_app/_admin/admin.orders'
import { Route as AppAdminAdminDistributorsRouteImport } from './routes/_app/_admin/admin.distributors'
import { Route as AppAdminAdminActivityRouteImport } from './routes/_app/_admin/admin.activity'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuickOrderRoute = AppQuickOrderRouteImport.update({
  id: '/quick-order',
  path: '/quick-order',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppAdminAdminIndexRoute = AppAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminTerritoriesRoute =
  AppAdminAdminTerritoriesRouteImport.update({
    id: '/admin/territories',
    path: '/admin/territories',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminAdminProductsRoute = AppAdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminOrdersRoute = AppAdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminDistributorsRoute =
  AppAdminAdminDistributorsRouteImport.update({
    id: '/admin/distributors',
    path: '/admin/distributors',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminAdminActivityRoute = AppAdminAdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/orders': typeof AppOrdersRoute
  '/products': typeof AppProductsRouteWithChildren
  '/quick-order': typeof AppQuickOrderRoute
  '/settings': typeof AppSettingsRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/admin/activity': typeof AppAdminAdminActivityRoute
  '/admin/distributors': typeof AppAdminAdminDistributorsRoute
  '/admin/orders': typeof AppAdminAdminOrdersRoute
  '/admin/products': typeof AppAdminAdminProductsRoute
  '/admin/territories': typeof AppAdminAdminTerritoriesRoute
  '/admin/': typeof AppAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/loyalty': typeof AppLoyaltyRoute
  '/orders': typeof AppOrdersRoute
  '/products': typeof AppProductsRouteWithChildren
  '/quick-order': typeof AppQuickOrderRoute
  '/settings': typeof AppSettingsRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/admin/activity': typeof AppAdminAdminActivityRoute
  '/admin/distributors': typeof AppAdminAdminDistributorsRoute
  '/admin/orders': typeof AppAdminAdminOrdersRoute
  '/admin/products': typeof AppAdminAdminProductsRoute
  '/admin/territories': typeof AppAdminAdminTerritoriesRoute
  '/admin': typeof AppAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/loyalty': typeof AppLoyaltyRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/products': typeof AppProductsRouteWithChildren
  '/_app/quick-order': typeof AppQuickOrderRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/_admin/admin/activity': typeof AppAdminAdminActivityRoute
  '/_app/_admin/admin/distributors': typeof AppAdminAdminDistributorsRoute
  '/_app/_admin/admin/orders': typeof AppAdminAdminOrdersRoute
  '/_app/_admin/admin/products': typeof AppAdminAdminProductsRoute
  '/_app/_admin/admin/territories': typeof AppAdminAdminTerritoriesRoute
  '/_app/_admin/admin/': typeof AppAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/loyalty'
    | '/orders'
    | '/products'
    | '/quick-order'
    | '/settings'
    | '/products/$productId'
    | '/admin/activity'
    | '/admin/distributors'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/territories'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/loyalty'
    | '/orders'
    | '/products'
    | '/quick-order'
    | '/settings'
    | '/products/$productId'
    | '/admin/activity'
    | '/admin/distributors'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/territories'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_app/_admin'
    | '/_app/dashboard'
    | '/_app/loyalty'
    | '/_app/orders'
    | '/_app/products'
    | '/_app/quick-order'
    | '/_app/settings'
    | '/_app/products/$productId'
    | '/_app/_admin/admin/activity'
    | '/_app/_admin/admin/distributors'
    | '/_app/_admin/admin/orders'
    | '/_app/_admin/admin/products'
    | '/_app/_admin/admin/territories'
    | '/_app/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quick-order': {
      id: '/_app/quick-order'
      path: '/quick-order'
      fullPath: '/quick-order'
      preLoaderRoute: typeof AppQuickOrderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loyalty': {
      id: '/_app/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/_admin/admin/': {
      id: '/_app/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/territories': {
      id: '/_app/_admin/admin/territories'
      path: '/admin/territories'
      fullPath: '/admin/territories'
      preLoaderRoute: typeof AppAdminAdminTerritoriesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/products': {
      id: '/_app/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AppAdminAdminProductsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/orders': {
      id: '/_app/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AppAdminAdminOrdersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/distributors': {
      id: '/_app/_admin/admin/distributors'
      path: '/admin/distributors'
      fullPath: '/admin/distributors'
      preLoaderRoute: typeof AppAdminAdminDistributorsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/activity': {
      id: '/_app/_admin/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AppAdminAdminActivityRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAdminActivityRoute: typeof AppAdminAdminActivityRoute
  AppAdminAdminDistributorsRoute: typeof AppAdminAdminDistributorsRoute
  AppAdminAdminOrdersRoute: typeof AppAdminAdminOrdersRoute
  AppAdminAdminProductsRoute: typeof AppAdminAdminProductsRoute
  AppAdminAdminTerritoriesRoute: typeof AppAdminAdminTerritoriesRoute
  AppAdminAdminIndexRoute: typeof AppAdminAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAdminActivityRoute: AppAdminAdminActivityRoute,
  AppAdminAdminDistributorsRoute: AppAdminAdminDistributorsRoute,
  AppAdminAdminOrdersRoute: AppAdminAdminOrdersRoute,
  AppAdminAdminProductsRoute: AppAdminAdminProductsRoute,
  AppAdminAdminTerritoriesRoute: AppAdminAdminTerritoriesRoute,
  AppAdminAdminIndexRoute: AppAdminAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsProductIdRoute: AppProductsProductIdRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppQuickOrderRoute: typeof AppQuickOrderRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppQuickOrderRoute: AppQuickOrderRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
